baseURL: https://zpyg.github.io/blog/
languageCode: zh-cn
theme: hugo-theme-stack
paginate: 5
title: pu's blog

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

DefaultContentLanguage: zh-cn

hasCJKLanguage: true

permalinks:
  post: /p/:slug/
  page: /:slug/

params:
  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true
  favicon: favicon.ico

  footer:
    since: 2020
    customText:

  dateFormat:
    published: 2006年1月2日 15:04:05
    lastUpdated: 2006年1月2日 15:04:05

  sidebar:
    emoji: ☀️
    subtitle: 有一分热，发一分光
    avatar:
      enabled: true
      local: false
      src: http://qzapp.qlogo.cn/qzapp/101284669/09BB0A59290ED59E41E96AFB214AEE72/100

  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: true
      default: Licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)

  comments:
    enabled: true
    provider: utterances

    utterances:
      repo: zpyg/blog
      issueTerm: pathname
      label: comment

  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  opengraph:
    twitter:
      # Your Twitter username
      site:

      # Available values: summary, summary_large_image
      card: summary_large_image

  defaultImage:
    opengraph:
      enabled: false
      local: false
      src:

  colorScheme:
    # Display toggle
    toggle: true

    # Available values: auto, light, dark
    default: dark

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
  main: []

  social:
    - identifier: email
      name: Email
      url: mailto:pu.mb@qq.com
      params:
        icon: envelope-solid

    - identifier: github
      name: GitHub
      url: https://github.com/zpyg
      params:
        icon: brand-github

    - identifier: telegram
      name: Telegram
      url: https://t.me/zpygtg
      params:
        icon: brand-telegram

    - identifier: bilibili
      name: BiliBili
      url: https://space.bilibili.com/336609200
      params:
        icon: brand-bilibili

    - identifier: qq
      name: QQ
      url: https://qm.qq.com/cgi-bin/qm/qr?k=b8SSH9x81dQ5Li7yVaAfV4j75cFjg3i1&noverify=0
      params:
        icon: brand-qq

    - identifier: weixin
      name: WeiXin
      url: /weixin.html
      params:
        icon: brand-weixin

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

markup:
  goldmark:
    renderer:
      ## Set to true if you have HTML content inside Markdown
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: true
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
    style: gruvbox
